//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.20 at 09:38:22 AM BST 
//


package uk.ac.ebi.intenz.tools.export.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bookType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bookType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebi.ac.uk/intenz}paperRefType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ebi.ac.uk/intenz}editorial"/>
 *         &lt;element name="edition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="editor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookType", propOrder = {
    "editorial",
    "edition",
    "editor"
})
public class BookType
    extends PaperRefType
{

    @XmlElement(namespace = "http://www.ebi.ac.uk/intenz", required = true)
    protected Editorial editorial;
    @XmlElement(namespace = "http://www.ebi.ac.uk/intenz", required = true)
    protected String edition;
    @XmlElement(namespace = "http://www.ebi.ac.uk/intenz", required = true)
    protected String editor;

    /**
     * Gets the value of the editorial property.
     * 
     * @return
     *     possible object is
     *     {@link Editorial }
     *     
     */
    public Editorial getEditorial() {
        return editorial;
    }

    /**
     * Sets the value of the editorial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Editorial }
     *     
     */
    public void setEditorial(Editorial value) {
        this.editorial = value;
    }

    /**
     * Gets the value of the edition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdition(String value) {
        this.edition = value;
    }

    /**
     * Gets the value of the editor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditor() {
        return editor;
    }

    /**
     * Sets the value of the editor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditor(String value) {
        this.editor = value;
    }

}
