//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.20 at 09:38:22 AM BST 
//


package uk.ac.ebi.intenz.tools.export.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Enzyme class type.
 * 
 * <p>Java class for ecClassType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ecClassType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ebi.ac.uk/intenz}name" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebi.ac.uk/intenz}description" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebi.ac.uk/intenz}ec_subclass" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ec1" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ecClassType", propOrder = {
    "name",
    "description",
    "ecSubclass"
})
public class EcClassType {

    @XmlElement(namespace = "http://www.ebi.ac.uk/intenz")
    protected XmlContentType name;
    @XmlElement(namespace = "http://www.ebi.ac.uk/intenz")
    protected XmlContentType description;
    @XmlElement(name = "ec_subclass", namespace = "http://www.ebi.ac.uk/intenz", required = true)
    protected List<EcSubclassType> ecSubclass;
    @XmlAttribute(required = true)
    protected BigInteger ec1;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link XmlContentType }
     *     
     */
    public XmlContentType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlContentType }
     *     
     */
    public void setName(XmlContentType value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link XmlContentType }
     *     
     */
    public XmlContentType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlContentType }
     *     
     */
    public void setDescription(XmlContentType value) {
        this.description = value;
    }

    /**
     * Gets the value of the ecSubclass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ecSubclass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEcSubclass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EcSubclassType }
     * 
     * 
     */
    public List<EcSubclassType> getEcSubclass() {
        if (ecSubclass == null) {
            ecSubclass = new ArrayList<EcSubclassType>();
        }
        return this.ecSubclass;
    }

    /**
     * Gets the value of the ec1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEc1() {
        return ec1;
    }

    /**
     * Sets the value of the ec1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEc1(BigInteger value) {
        this.ec1 = value;
    }

}
