//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.20 at 09:38:22 AM BST 
//


package uk.ac.ebi.intenz.tools.export.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * A name for the enzyme.
 * 
 * <p>Java class for enzymeNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="enzymeNameType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebi.ac.uk/intenz}viewableType">
 *       &lt;attribute name="qualifier" type="{http://www.ebi.ac.uk/intenz}enzymeNameQualifierType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enzymeNameType")
public class EnzymeNameType
    extends ViewableType
{

    @XmlAttribute
    protected EnzymeNameQualifierType qualifier;

    /**
     * Gets the value of the qualifier property.
     * 
     * @return
     *     possible object is
     *     {@link EnzymeNameQualifierType }
     *     
     */
    public EnzymeNameQualifierType getQualifier() {
        return qualifier;
    }

    /**
     * Sets the value of the qualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnzymeNameQualifierType }
     *     
     */
    public void setQualifier(EnzymeNameQualifierType value) {
        this.qualifier = value;
    }

}
