//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.20 at 09:38:22 AM BST 
//


package uk.ac.ebi.intenz.tools.export.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Bibliographic references to the enzyme.
 * 
 * <p>Java class for references element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="references">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://www.ebi.ac.uk/intenz}book"/>
 *           &lt;element ref="{http://www.ebi.ac.uk/intenz}journal"/>
 *           &lt;element ref="{http://www.ebi.ac.uk/intenz}patent"/>
 *         &lt;/choice>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bookOrJournalOrPatent"
})
@XmlRootElement(name = "references")
public class References {

    @XmlElements({
        @XmlElement(name = "patent", namespace = "http://www.ebi.ac.uk/intenz", required = true, type = PatentType.class),
        @XmlElement(name = "journal", namespace = "http://www.ebi.ac.uk/intenz", required = true, type = JournalType.class),
        @XmlElement(name = "book", namespace = "http://www.ebi.ac.uk/intenz", required = true, type = BookType.class)
    })
    protected List<ReferenceType> bookOrJournalOrPatent;

    /**
     * Gets the value of the bookOrJournalOrPatent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bookOrJournalOrPatent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBookOrJournalOrPatent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatentType }
     * {@link JournalType }
     * {@link BookType }
     * 
     * 
     */
    public List<ReferenceType> getBookOrJournalOrPatent() {
        if (bookOrJournalOrPatent == null) {
            bookOrJournalOrPatent = new ArrayList<ReferenceType>();
        }
        return this.bookOrJournalOrPatent;
    }

}
