//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.20 at 09:38:22 AM BST 
//


package uk.ac.ebi.intenz.tools.export.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for viewType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="viewType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INTENZ"/>
 *     &lt;enumeration value="IUBMB"/>
 *     &lt;enumeration value="SIB"/>
 *     &lt;enumeration value="INTENZ,IUBMB"/>
 *     &lt;enumeration value="INTENZ,SIB"/>
 *     &lt;enumeration value="IUBMB,SIB"/>
 *     &lt;enumeration value="INTENZ,IUBMB,SIB"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ViewType {

    INTENZ("INTENZ"),
    @XmlEnumValue("INTENZ,IUBMB")
    INTENZ_IUBMB("INTENZ,IUBMB"),
    @XmlEnumValue("INTENZ,IUBMB,SIB")
    INTENZ_IUBMB_SIB("INTENZ,IUBMB,SIB"),
    @XmlEnumValue("INTENZ,SIB")
    INTENZ_SIB("INTENZ,SIB"),
    IUBMB("IUBMB"),
    @XmlEnumValue("IUBMB,SIB")
    IUBMB_SIB("IUBMB,SIB"),
    SIB("SIB");
    private final String value;

    ViewType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ViewType fromValue(String v) {
        for (ViewType c: ViewType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
