//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.20 at 09:38:22 AM BST 
//


package uk.ac.ebi.intenz.tools.export.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for enzymeNameQualifierType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enzymeNameQualifierType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ambiguous"/>
 *     &lt;enumeration value="incorrect"/>
 *     &lt;enumeration value="misleading"/>
 *     &lt;enumeration value="misprint"/>
 *     &lt;enumeration value="obsolete"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum EnzymeNameQualifierType {

    @XmlEnumValue("ambiguous")
    AMBIGUOUS("ambiguous"),
    @XmlEnumValue("incorrect")
    INCORRECT("incorrect"),
    @XmlEnumValue("misleading")
    MISLEADING("misleading"),
    @XmlEnumValue("misprint")
    MISPRINT("misprint"),
    @XmlEnumValue("obsolete")
    OBSOLETE("obsolete");
    private final String value;

    EnzymeNameQualifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnzymeNameQualifierType fromValue(String v) {
        for (EnzymeNameQualifierType c: EnzymeNameQualifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
