//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.20 at 09:38:22 AM BST 
//


package uk.ac.ebi.intenz.tools.export.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * The IntEnz database.
 * 
 * <p>Java class for intenz element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="intenz">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="data_description" type="{http://www.ebi.ac.uk/intenz}xmlContentType" minOccurs="0"/>
 *           &lt;element ref="{http://www.ebi.ac.uk/intenz}ec_class" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *         &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *         &lt;attribute name="release" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataDescription",
    "ecClass"
})
@XmlRootElement(name = "intenz")
public class Intenz {

    @XmlElement(name = "data_description", namespace = "http://www.ebi.ac.uk/intenz")
    protected XmlContentType dataDescription;
    @XmlElement(name = "ec_class", namespace = "http://www.ebi.ac.uk/intenz", required = true)
    protected List<EcClassType> ecClass;
    @XmlAttribute(required = true)
    protected XMLGregorianCalendar date;
    @XmlAttribute(required = true)
    protected BigInteger release;

    /**
     * Gets the value of the dataDescription property.
     * 
     * @return
     *     possible object is
     *     {@link XmlContentType }
     *     
     */
    public XmlContentType getDataDescription() {
        return dataDescription;
    }

    /**
     * Sets the value of the dataDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlContentType }
     *     
     */
    public void setDataDescription(XmlContentType value) {
        this.dataDescription = value;
    }

    /**
     * Gets the value of the ecClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ecClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEcClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EcClassType }
     * 
     * 
     */
    public List<EcClassType> getEcClass() {
        if (ecClass == null) {
            ecClass = new ArrayList<EcClassType>();
        }
        return this.ecClass;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the release property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRelease() {
        return release;
    }

    /**
     * Sets the value of the release property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRelease(BigInteger value) {
        this.release = value;
    }

}
