//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.20 at 09:38:22 AM BST 
//


package uk.ac.ebi.intenz.tools.export.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ebi.intenz.tools.export.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Comment_QNAME = new QName("http://www.ebi.ac.uk/intenz", "comment");
    private final static QName _Journal_QNAME = new QName("http://www.ebi.ac.uk/intenz", "journal");
    private final static QName _SystematicName_QNAME = new QName("http://www.ebi.ac.uk/intenz", "systematic_name");
    private final static QName _EcClass_QNAME = new QName("http://www.ebi.ac.uk/intenz", "ec_class");
    private final static QName _Book_QNAME = new QName("http://www.ebi.ac.uk/intenz", "book");
    private final static QName _Link_QNAME = new QName("http://www.ebi.ac.uk/intenz", "link");
    private final static QName _EcSubclass_QNAME = new QName("http://www.ebi.ac.uk/intenz", "ec_subclass");
    private final static QName _Deleted_QNAME = new QName("http://www.ebi.ac.uk/intenz", "deleted");
    private final static QName _Synonym_QNAME = new QName("http://www.ebi.ac.uk/intenz", "synonym");
    private final static QName _Cofactor_QNAME = new QName("http://www.ebi.ac.uk/intenz", "cofactor");
    private final static QName _Enzyme_QNAME = new QName("http://www.ebi.ac.uk/intenz", "enzyme");
    private final static QName _Patent_QNAME = new QName("http://www.ebi.ac.uk/intenz", "patent");
    private final static QName _AcceptedName_QNAME = new QName("http://www.ebi.ac.uk/intenz", "accepted_name");
    private final static QName _Description_QNAME = new QName("http://www.ebi.ac.uk/intenz", "description");
    private final static QName _Transferred_QNAME = new QName("http://www.ebi.ac.uk/intenz", "transferred");
    private final static QName _Reaction_QNAME = new QName("http://www.ebi.ac.uk/intenz", "reaction");
    private final static QName _EcSubSubclass_QNAME = new QName("http://www.ebi.ac.uk/intenz", "ec_sub-subclass");
    private final static QName _Ec_QNAME = new QName("http://www.ebi.ac.uk/intenz", "ec");
    private final static QName _Name_QNAME = new QName("http://www.ebi.ac.uk/intenz", "name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ebi.intenz.tools.export.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cofactors }
     * 
     */
    public Cofactors createCofactors() {
        return new Cofactors();
    }

    /**
     * Create an instance of {@link Links }
     * 
     */
    public Links createLinks() {
        return new Links();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link Comments }
     * 
     */
    public Comments createComments() {
        return new Comments();
    }

    /**
     * Create an instance of {@link EcClassType }
     * 
     */
    public EcClassType createEcClassType() {
        return new EcClassType();
    }

    /**
     * Create an instance of {@link Reactions }
     * 
     */
    public Reactions createReactions() {
        return new Reactions();
    }

    /**
     * Create an instance of {@link InactiveStatusType }
     * 
     */
    public InactiveStatusType createInactiveStatusType() {
        return new InactiveStatusType();
    }

    /**
     * Create an instance of {@link BookType }
     * 
     */
    public BookType createBookType() {
        return new BookType();
    }

    /**
     * Create an instance of {@link ViewableType }
     * 
     */
    public ViewableType createViewableType() {
        return new ViewableType();
    }

    /**
     * Create an instance of {@link ReactionType }
     * 
     */
    public ReactionType createReactionType() {
        return new ReactionType();
    }

    /**
     * Create an instance of {@link Intenz }
     * 
     */
    public Intenz createIntenz() {
        return new Intenz();
    }

    /**
     * Create an instance of {@link CofactorType }
     * 
     */
    public CofactorType createCofactorType() {
        return new CofactorType();
    }

    /**
     * Create an instance of {@link EnzymeType }
     * 
     */
    public EnzymeType createEnzymeType() {
        return new EnzymeType();
    }

    /**
     * Create an instance of {@link EcSubsubclassType }
     * 
     */
    public EcSubsubclassType createEcSubsubclassType() {
        return new EcSubsubclassType();
    }

    /**
     * Create an instance of {@link Synonyms }
     * 
     */
    public Synonyms createSynonyms() {
        return new Synonyms();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link PatentType }
     * 
     */
    public PatentType createPatentType() {
        return new PatentType();
    }

    /**
     * Create an instance of {@link EnzymeNameType }
     * 
     */
    public EnzymeNameType createEnzymeNameType() {
        return new EnzymeNameType();
    }

    /**
     * Create an instance of {@link JournalType }
     * 
     */
    public JournalType createJournalType() {
        return new JournalType();
    }

    /**
     * Create an instance of {@link EcSubclassType }
     * 
     */
    public EcSubclassType createEcSubclassType() {
        return new EcSubclassType();
    }

    /**
     * Create an instance of {@link Editorial }
     * 
     */
    public Editorial createEditorial() {
        return new Editorial();
    }

    /**
     * Create an instance of {@link XmlContentType }
     * 
     */
    public XmlContentType createXmlContentType() {
        return new XmlContentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ViewableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "comment")
    public JAXBElement<ViewableType> createComment(ViewableType value) {
        return new JAXBElement<ViewableType>(_Comment_QNAME, ViewableType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JournalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "journal")
    public JAXBElement<JournalType> createJournal(JournalType value) {
        return new JAXBElement<JournalType>(_Journal_QNAME, JournalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnzymeNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "systematic_name")
    public JAXBElement<EnzymeNameType> createSystematicName(EnzymeNameType value) {
        return new JAXBElement<EnzymeNameType>(_SystematicName_QNAME, EnzymeNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EcClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "ec_class")
    public JAXBElement<EcClassType> createEcClass(EcClassType value) {
        return new JAXBElement<EcClassType>(_EcClass_QNAME, EcClassType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "book")
    public JAXBElement<BookType> createBook(BookType value) {
        return new JAXBElement<BookType>(_Book_QNAME, BookType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "link")
    public JAXBElement<LinkType> createLink(LinkType value) {
        return new JAXBElement<LinkType>(_Link_QNAME, LinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EcSubclassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "ec_subclass")
    public JAXBElement<EcSubclassType> createEcSubclass(EcSubclassType value) {
        return new JAXBElement<EcSubclassType>(_EcSubclass_QNAME, EcSubclassType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InactiveStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "deleted")
    public JAXBElement<InactiveStatusType> createDeleted(InactiveStatusType value) {
        return new JAXBElement<InactiveStatusType>(_Deleted_QNAME, InactiveStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnzymeNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "synonym")
    public JAXBElement<EnzymeNameType> createSynonym(EnzymeNameType value) {
        return new JAXBElement<EnzymeNameType>(_Synonym_QNAME, EnzymeNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CofactorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "cofactor")
    public JAXBElement<CofactorType> createCofactor(CofactorType value) {
        return new JAXBElement<CofactorType>(_Cofactor_QNAME, CofactorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnzymeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "enzyme")
    public JAXBElement<EnzymeType> createEnzyme(EnzymeType value) {
        return new JAXBElement<EnzymeType>(_Enzyme_QNAME, EnzymeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "patent")
    public JAXBElement<PatentType> createPatent(PatentType value) {
        return new JAXBElement<PatentType>(_Patent_QNAME, PatentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnzymeNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "accepted_name")
    public JAXBElement<EnzymeNameType> createAcceptedName(EnzymeNameType value) {
        return new JAXBElement<EnzymeNameType>(_AcceptedName_QNAME, EnzymeNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "description")
    public JAXBElement<XmlContentType> createDescription(XmlContentType value) {
        return new JAXBElement<XmlContentType>(_Description_QNAME, XmlContentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InactiveStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "transferred")
    public JAXBElement<InactiveStatusType> createTransferred(InactiveStatusType value) {
        return new JAXBElement<InactiveStatusType>(_Transferred_QNAME, InactiveStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "reaction")
    public JAXBElement<ReactionType> createReaction(ReactionType value) {
        return new JAXBElement<ReactionType>(_Reaction_QNAME, ReactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EcSubsubclassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "ec_sub-subclass")
    public JAXBElement<EcSubsubclassType> createEcSubSubclass(EcSubsubclassType value) {
        return new JAXBElement<EcSubsubclassType>(_EcSubSubclass_QNAME, EcSubsubclassType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "ec")
    public JAXBElement<String> createEc(String value) {
        return new JAXBElement<String>(_Ec_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/intenz", name = "name")
    public JAXBElement<XmlContentType> createName(XmlContentType value) {
        return new JAXBElement<XmlContentType>(_Name_QNAME, XmlContentType.class, null, value);
    }

}
