//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.20 at 09:38:22 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ebi.ac.uk/intenz")
package uk.ac.ebi.intenz.tools.export.jaxb;
